spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306?useSSL-=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: YoungKbt1234
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 1
    host: 8.129.212.155
    #    host: localhost
    port: 6379
    timeout: 500
    password: chenyicai0819