server:
  port: 8095

spring:
  profiles:
    active: dev

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:log.xml
  
jwt-token:
  username: sub
  created: created
  authorities: authorities
  secret-key: generic
  expire-time: 43200000 # 12 小时
